module.exports = function actionSelf(context,data) {
	return context.waitForExist(data.item, 50000)
			.scroll(data.item)
			.click(data.sizes.size1)
			.pause(2000)
			.setValue(data.phoneSingle, data.phoneVal)
			/*.click(sizes.size2)
			.click(sizes.size3)
			.click(sizes.size4)
			.setValue(config.contract.phoneSingle, config.contract.phoneVal)
			.pause(1000)
			.click(config.contract.sand)
			.pause(1000)
			.waitForExist(config.contract.validateMsg, 5000)
			.getText(config.contract.validateMsg)
			.then(function(text) {
            assert.equal(text, 'Введите корректный телефон!')
      })
			.pause(1000)
			.click(sizes.size3)
			.pause(1000)*/
			//.setValue(config.contract.phoneSingle,'')
			//.setValue(config.contract.phoneSingle, config.contract.phoneVal)
			//.waitForExist('.spinner_block', 50000)
			//.pause(4000)
			//.click(sizes.size3)
			//.pause(2000)
			//.click(config.contract.checkbox)
			//.pause(2000)

}